# Generated by Django 4.0.4 on 2022-04-18 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar_app', '0004_bar_beer_tap_taparchive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_owner',
            field=models.BooleanField(default=False, verbose_name='is a bar owner'),
        ),
    ]
