# Generated by Django 4.0.4 on 2022-04-19 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar_app', '0006_delete_tap_delete_taparchive_bar_name_bar_num_taps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='date_finished',
            field=models.DateField(blank=True, null=True),
        ),
    ]
