# Generated by Django 4.0.4 on 2022-04-19 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar_app', '0007_alter_beer_date_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
    ]
