# Generated by Django 4.0.4 on 2022-04-20 03:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bar_app', '0009_alter_bar_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bar',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bar', to=settings.AUTH_USER_MODEL),
        ),
    ]
