# Generated by Django 4.0.4 on 2022-04-20 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bar_app', '0010_alter_bar_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_owner',
        ),
    ]
