# Generated by Django 4.0.4 on 2022-04-20 17:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar_app', '0011_remove_user_is_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beer',
            name='quantity_remaining',
        ),
        migrations.AlterField(
            model_name='beer',
            name='batch_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='beer',
            name='quantity_start',
            field=models.IntegerField(default=640, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='beer',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='beer',
            name='tap',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
