# Generated by Django 4.0.4 on 2022-04-20 20:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar_app', '0012_remove_beer_quantity_remaining_alter_beer_batch_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='tap',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
