# Generated by Django 4.0.4 on 2022-04-20 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar_app', '0013_alter_beer_tap'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
