# Generated by Django 4.0.4 on 2022-04-21 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar_app', '0014_beer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bf_api_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='bf_api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
