# Generated by Django 4.0.4 on 2022-04-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar_app', '0018_remove_beer_brew_date_remove_beer_keg_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='brew_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beer',
            name='keg_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
