# Generated by Django 4.0.4 on 2022-04-21 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bar_app', '0020_user_bf_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bf_api_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bf_api_key',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bf_user',
        ),
    ]
