# Generated by Django 4.0.4 on 2022-04-21 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar_app', '0022_user_bf_api_id_user_bf_api_key_user_bf_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bf_user',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
