# Generated by Django 4.0.4 on 2022-04-23 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar_app', '0023_alter_user_bf_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='abv',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
