# Generated by Django 4.0.4 on 2022-04-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar_app', '0024_alter_beer_abv'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='description',
            field=models.TextField(default='A delicious beer'),
        ),
    ]
