# Generated by Django 4.0.4 on 2022-04-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar_app', '0025_beer_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='style',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='beer',
            name='style_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
