# Generated by Django 4.0.4 on 2022-04-24 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar_app', '0029_alter_user_favorite_bars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favorite_bars',
            field=models.ManyToManyField(blank=True, related_name='visitors', to='bar_app.bar'),
        ),
    ]
