# Generated by Django 4.0.4 on 2022-04-25 01:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bar_app', '0030_alter_user_favorite_bars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favorite_bars',
        ),
        migrations.CreateModel(
            name='FavoriteBars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_visitors', to='bar_app.bar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_bars', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'bar')},
            },
        ),
    ]
