# Generated by Django 4.0.4 on 2022-04-25 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar_app', '0031_remove_user_favorite_bars_favoritebars'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_bars',
            field=models.ManyToManyField(related_name='visitor', to='bar_app.bar'),
        ),
        migrations.DeleteModel(
            name='FavoriteBars',
        ),
    ]
