# Generated by Django 4.0.4 on 2022-04-25 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar_app', '0032_user_favorite_bars_delete_favoritebars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favorite_bars',
            field=models.ManyToManyField(blank=True, related_name='visitor', to='bar_app.bar'),
        ),
    ]
