# Generated by Django 4.0.4 on 2022-04-25 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bar_app', '0033_alter_user_favorite_bars'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeerStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drinker_stats', to='bar_app.beer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_beers_stats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
