# Generated by Django 4.0.4 on 2022-04-25 15:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar_app', '0034_beerstat'),
    ]

    operations = [
        migrations.AddField(
            model_name='beerstat',
            name='quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
