# Generated by Django 4.0.4 on 2022-04-25 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bar_app', '0035_beerstat_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beerstat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_beer_stats', to=settings.AUTH_USER_MODEL),
        ),
    ]
