import { Button, Modal, Form } from "react-bootstrap";
import { useState } from "react";
import { useForm } from "react-hook-form";
import { yupResolver } from '@hookform/resolvers/yup'
import * as Yup from 'yup'
import AuthAPI from "../../utils/auth_utils";

function AddBFModal(props) {

    const [show, setShow] = useState(false);

    const handleClose = () => setShow(false);
    const handleShow = () => setShow(true);

    const formSchema = Yup.object().shape({
        bf_api_id: Yup.string()
          .required('Email is required'),
        bf_api_key: Yup.string()
          .required('First name is required')
    })
    const validationOpt = { resolver: yupResolver(formSchema) }
    const { register, handleSubmit, formState: { errors } } = useForm(validationOpt)

    const submitCreds = async (data)=>{
        let response = await AuthAPI.bfCreds(props.user.id, data)
        if (response){
            props.setUser(response)
            handleClose()
        }
    }

    const credsForm = ()=>{
        return (
            <>
                <Form.Group className="mb-3" controlId="formApiId">
                    <Form.Label>Brewfather API ID</Form.Label>
                    <Form.Control {...register("bf_api_id")} type="password" placeholder="Enter your API Id generated by Brewfather" />
                    {errors.apiId && <small className="form-error">{errors.apiId?.message}</small>}
                </Form.Group>
                <Form.Group className="mb-3" controlId="formApiKey">
                    <Form.Label>Brewfather API Key</Form.Label>
                    <Form.Control {...register("bf_api_key")} type="password" placeholder="Enter your API Key generated by Brewfather" />
                    {errors.apiKey && <small className="form-error">{errors.apiKey?.message}</small>}
                </Form.Group>
            </>
        )
    }

    return (
        <div className="content-center">
            <Button variant="warning" onClick={handleShow}>Add/Edit BrewFather Credentials</Button>
            <Modal show={show} onHide={handleClose}>
                <Modal.Header closeButton>
                <Modal.Title>Import from BrewFather</Modal.Title>
                </Modal.Header>
                <Form onSubmit={handleSubmit(submitCreds)}>
                <Modal.Body>
                    If you would like to enable access to import Brew Sessions from BrewFather enter the required info below. If you arent sure how to get this check out this <a target="_blank" href="https://docs.brewfather.app/api">link</a> for instructions
                    <p></p>
                    { credsForm() }
                </Modal.Body>
                <Modal.Footer>
                <Button variant="secondary" onClick={handleClose}>
                    Close
                </Button>
                <Button variant="warning" type="submit">
                    Save
                </Button>
                </Modal.Footer>
                </Form>
            </Modal>
        </div>
    );
}

export default AddBFModal;